# Generated by Django 4.0.3 on 2022-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30, unique=True)),
                ("description", models.CharField(max_length=20)),
                ("temperature", models.IntegerField()),
                ("precipitation", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("wind_direction", models.CharField(max_length=10)),
                ("wind_speed", models.IntegerField()),
                ("humidity", models.IntegerField()),
            ],
        ),
    ]
