# Generated by Django 4.0.3 on 2022-04-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show_weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="city",
            new_name="location",
        ),
    ]
